server:
  port: 8084

spring:
  application:
    name: workout-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/gymplan_workout}
      auto-index-creation: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3
      properties:
        linger.ms: 10
        batch.size: 32768
        compression.type: snappy

gymplan:
  jwt:
    issuer: gymplan
    public-key: ${JWT_PUBLIC_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true
  metrics:
    tags:
      application: workout-service
      namespace: gymplan-prod

logging:
  level:
    com.gymplan.workout: INFO
