image:
  repository: ghcr.io/lorehes/gymplan/analytics-service

service:
  port: 8085
  targetPort: 8085

vault:
  role: gymplan-analytics-service
  agentEnvTemplate: |
    {{- with secret "secret/data/gymplan/elasticsearch" -}}
    export ES_USERNAME='{{ .Data.data.username }}'
    export ES_PASSWORD='{{ .Data.data.password }}'
    {{- end }}
    {{- with secret "secret/data/gymplan/kafka" -}}
    export KAFKA_USERNAME='{{ .Data.data.username }}'
    export KAFKA_PASSWORD='{{ .Data.data.password }}'
    {{- end }}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s
