image:
  repository: ghcr.io/lorehes/gymplan/api-gateway

service:
  port: 8080
  targetPort: 8080

resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi

vault:
  role: gymplan-api-gateway
  agentEnvTemplate: |
    {{- with secret "secret/data/gymplan/redis" -}}
    export REDIS_PASSWORD='{{ .Data.data.password }}'
    {{- end }}
    {{- with secret "secret/data/gymplan/jwt" -}}
    export JWT_PUBLIC_KEY='{{ .Data.data.public-key }}'
    {{- end }}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s
