image:
  repository: ghcr.io/lorehes/gymplan/notification-service

service:
  port: 8086
  targetPort: 8086

vault:
  role: gymplan-notification-service
  agentEnvTemplate: |
    {{- with secret "secret/data/gymplan/redis" -}}
    export REDIS_PASSWORD='{{ .Data.data.password }}'
    {{- end }}
    {{- with secret "secret/data/gymplan/kafka" -}}
    export KAFKA_USERNAME='{{ .Data.data.username }}'
    export KAFKA_PASSWORD='{{ .Data.data.password }}'
    {{- end }}
    export FCM_SERVICE_ACCOUNT_PATH='/vault/secrets/fcm-sa.json'
  fcmTemplate: |
    {{- with secret "secret/data/gymplan/fcm" -}}
    {{ .Data.data.service-account-json }}
    {{- end }}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: k8s
